### ISSUE TITLE
Container padding

### ISSUE THREAD

**Issue by cyouh95** [flynncreek/TeaCozy#3]
Alternatively, you could add padding to your `featured` div container to create the extra spacing.

```css
.featured {
  padding: 50px 0px;
  ...
}
```

https://github.com/flynncreek/TeaCozy/blob/master/index.html#L51-L52
https://github.com/flynncreek/TeaCozy/blob/master/resources/css/style.css#L101-L108
